In [6]:
import numpy as np
#交换矩阵的其中两行
a = np.arange(25).reshape(5,5)
print a
a[[0,1]] = a[[1,0]]
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
#找出数组中与给定值最接近的数
z = np.array([[0,1,2,3],[4,5,6,7]])
a = 5.1
print np.abs(z-a).argmin()

5


In [9]:
#判断二维矩阵中有没有一整列数为0？
z = np.random.randint(0,3,(2,10))
print z
print z.any(axis=0)

[[1 1 2 0 0 1 1 0 2 2]
 [0 0 2 1 0 2 1 0 1 0]]
[ True  True  True  True False  True  True False  True  True]


In [15]:
#生成二维的高斯矩阵
help(np.random.randint)

Help on built-in function randint:

randint(...)
    randint(low, high=None, size=None)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution in the
    "half-open" interval [`low`, `high`). If `high` is None (the default),
    then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    

In [14]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
print x
print y
D = np.sqrt(x**2+y**2)
print D
sigma,mu = 1,0
a = np.exp(-(D-mu)**2/(2*sigma**2))
print a

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


In [2]:
import numpy as np
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.size

15

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,3,4),dtype = np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [9]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [10]:
np.random.random((2,3))

array([[0.49727851, 0.46492319, 0.73120795],
       [0.42984738, 0.58499333, 0.97155774]])

In [11]:
from numpy import pi
np.linspace(0,2*pi,100)#起始值为0 重点2Π 共计100个数

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [20]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)
c = a- b
print(c)
c = c - 1 
print(c)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 28 37 46]


In [29]:
a = a.reshape(2,2)
b = b.reshape(2,2)
print(a)
print(b)
print("-------按位相乘a*b-------")
print(a*b)
print("-----矩阵乘法------")
print(a.dot(b))
print(np.dot(a,b))

[[20 30]
 [40 50]]
[[0 1]
 [2 3]]
-------按位相乘a*b-------
[[  0  30]
 [ 80 150]]
-----矩阵乘法------
[[ 60 110]
 [100 190]]
[[ 60 110]
 [100 190]]


In [30]:
b = np.arange(3)
print(np.exp(b))

[1.         2.71828183 7.3890561 ]


In [38]:
a = np.floor(10*np.random.random((3,4)))
#random生成 -1 到 1 的随机值  floor 向下取整
print(a)
print(a.ravel())
#将 （m，n）变成 （m*n，1）
a.shape = (6,2)
print(a)
print(a.T)
a = a.reshape(3,-1)
#用-1 就会自动帮你转化成 3 行 某列的 矩阵
print(a)

[[0. 7. 8. 6.]
 [2. 6. 6. 1.]
 [4. 5. 6. 5.]]
[0. 7. 8. 6. 2. 6. 6. 1. 4. 5. 6. 5.]
[[0. 7.]
 [8. 6.]
 [2. 6.]
 [6. 1.]
 [4. 5.]
 [6. 5.]]
[[0. 8. 2. 6. 4. 6.]
 [7. 6. 6. 1. 5. 5.]]
[[0. 7. 8. 6.]
 [2. 6. 6. 1.]
 [4. 5. 6. 5.]]


In [42]:
a= np.floor(10*np.random.random((2,2)))
b= np.floor(10*np.random.random((2,2)))
print(a)
print('---------')
print(b)
print(np.hstack((a,b))) #横着拼接
print(np.vstack((a,b)))#纵向拼接

[[4. 0.]
 [4. 2.]]
---------
[[7. 7.]
 [2. 9.]]
[[4. 0. 7. 7.]
 [4. 2. 2. 9.]]
[[4. 0.]
 [4. 2.]
 [7. 7.]
 [2. 9.]]


In [51]:
a= np.floor(10*np.random.random((2,12)))
print(a)
print('---')
print(np.hsplit(a,3))#横向切割 成三个(2,4)的array
print(np.hsplit(a,(3,4)))#在第3列 第4列切两刀




[[5. 2. 2. 9. 2. 6. 1. 7. 3. 2. 1. 3.]
 [6. 6. 2. 7. 9. 7. 9. 3. 5. 6. 8. 8.]]
---
[array([[5., 2., 2., 9.],
       [6., 6., 2., 7.]]), array([[2., 6., 1., 7.],
       [9., 7., 9., 3.]]), array([[3., 2., 1., 3.],
       [5., 6., 8., 8.]])]
[array([[5., 2., 2.],
       [6., 6., 2.]]), array([[9.],
       [7.]]), array([[2., 6., 1., 7., 3., 2., 1., 3.],
       [9., 7., 9., 3., 5., 6., 8., 8.]])]


In [58]:
a = np.arange(12)
b = a 
print(b is a )
b.shape=(3,4)
print(a.shape)
print(id(a))
print(id(b))
#地址相同

True
(3, 4)
2743940492384
2743940492384


In [60]:
c = a.view()
print(c is a)
c.shape = 2,6
print(a.shape)
c[0,4] = 123
print(a)
print(id(a))
print(id(c))
#地址不同 但是地址共用同一批数值

False
(3, 4)
[[  0   1   2   3]
 [123   5   6   7]
 [  8   9  10  11]]
2743940492384
2743940492944


In [61]:
d = a.copy()
print(d is a)
d[0,0]=999
print(a)
print(d)

False
[[  0   1   2   3]
 [123   5   6   7]
 [  8   9  10  11]]
[[999   1   2   3]
 [123   5   6   7]
 [  8   9  10  11]]


In [64]:
data = np.sin(np.arange(20).reshape(5,4))
print(data)
ind = data.argmax(axis = 0)#索引每列的最大值 
print(ind)
data_max = data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [67]:
a = np.arange(0,40,10)
print(a)
b = np.tile(a,(2,3))#行和列扩展成 2 ， 3 
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [74]:
a = np.array([[4,2,3],[1,2,0]])
print(a)
print(np.sort(a,axis = 1))
a = np.array([4,3,1,2])
print(np.argsort(a)) #排序值的索引
print(a[np.argsort(a)])

[[4 2 3]
 [1 2 0]]
[[2 3 4]
 [0 1 2]]
[2 3 1 0]
[1 2 3 4]


None
